name: CI/CD Pipeline
on:
   workflow_dispatch:
    inputs:
      tagid:
        description: 'Tag ID'     
        required: true

jobs:       
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1
    - name: Checkout to repo
      uses: actions/checkout@v2

      # Step 2
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
      #step 3
#       # Deploy push to AWS S3
    - name: AWS Deploy push
      run: |
         sudo apt-get -y update; sudo apt-get -y install git curl jq python3-pip; sudo apt-get -y install wget zip unzip
         sudo pip3 install -U awscli
         sudo curl -fsSL https://get.docker.com -o get-docker.sh
         git clone https://github.com/sasender/nodejs-aws-codedeploy-pipeline.git -b ${{github.event.inputs.tagid}}
         zip -r $GITHUB_SHA.zip nodejs-aws-codedeploy-pipeline
         ls -la
         pwd
         aws sts get-caller-identity
         aws s3 ls s3://sasender --recursive
         aws s3 cp $GITHUB_SHA.zip s3://sasender/
         aws deploy create-deployment \
         --application-name deploy-jhon \
         --deployment-group-name deploy-jhon \
         --deployment-config-name CodeDeployDefault.OneAtATime \
         --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
         #--s3-location bucket=sasender,key=$GITHUB_SHA.zip,bundleType=zip
